name: Create SBLT Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release

    - name: Build DLL
      run: |
        cd build
        msbuild SuperBLT.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SuperBLT-x64-DLL
        path: build/Release/WSOCK32.dll
